{
 "title": "Aerospike Kubernetes View",
 "description": "this dashboard helps to view stats of aerospike-server & exporter running in Kubernetes  using exporter tools like kube-state-metrics and cadvisor",
 "tags": [
  "monitoring",
  "kube-state-metrics",
  "c-advisor",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "K8S Cluster",
    "query": {
     "query": "label_values(kube_namespace_created,cluster_name)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values({__name__=~\"aerospike_node_stats_uptime\"},job)"
    }
   },
   {
    "name": "namespace",
    "label": "K8S Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster_name=\"$cluster_name\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "K8S Pod",
    "query": {
     "query": "label_values({__name__=~\"container.*\", namespace=~\"$namespace\", cluster_name=\"$cluster_name\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "K8S Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"},container)"
    }
   },
   {
    "name": "volume_claim",
    "label": "Peristent Volume Claim",
    "query": {
     "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "volume",
    "label": "Persistent Volume",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$volume_claim.*\", cluster_name=\"$cluster_name\", namespace=\"$namespace\"}, volumename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<b>NOTE: \n<br/>This dashboard requires Kube-state-metrics(KSM) and CAdvisor to be installed.\n<br/>If KSM is not configured, overview(KSM) Row will be blank and if CAdvisor is not configured, Pod(CAdvisor) Row will be blank. </b>\n<br/>Pod count in Overview(KSM) Row is cumulative of all pods in namespace irrespective of Aerospike cluster.\n</b>"
   }
  },
  {
   "title": "Stats - Kube State Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Count",
     "type": "stat",
     "description": "Cumulative count of pods in namespace irrespective of Aerospike cluster",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (kube_pod_info{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "k8s Namespace Created",
     "type": "stat",
     "description": "Time since when namespace is created",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - kube_namespace_created{namespace=~\"$namespace\", cluster_name=\"$cluster_name\"}",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Pod Container Status",
     "type": "stat",
     "description": "Status of container in pod Running/Terminated/Waiting/Restarts",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"})",
       "legendFormat": "Terminated"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "k8s Namespace Status",
     "type": "stat",
     "description": "Namespace status is active/terminating",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase) (kube_namespace_status_phase{namespace=~\"$namespace\", cluster_name=\"$cluster_name\"})",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Pod State",
     "type": "stat",
     "description": "Pod state is Failed/Pending/Running/Succeeded/Unknown",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase)(kube_pod_status_phase{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"})",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Pod State",
     "type": "timeseries",
     "description": "Pod state Running/Failed/Pending/Succeeded/Unknown in Time series",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}-{{phase}}"
      }
     ]
    },
    {
     "title": "Pod Container Status",
     "type": "timeseries",
     "description": "Status of container in pod Running/Terminated/Waiting in Time series",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_running{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}/{{container}}-Running"
      },
      {
       "expr": "kube_pod_container_status_waiting{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}/{{container}}-Waiting"
      },
      {
       "expr": "kube_pod_container_status_terminated{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}/{{container}}-Terminated"
      }
     ]
    },
    {
     "title": "Pod Container Restarts Total (rate)",
     "type": "timeseries",
     "description": "Rate of container restarts  in pod (Timeseries)",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "PV Info",
     "type": "stat",
     "description": "Persistent volume count",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_persistentvolume_info{persistentvolume=~\"$volume\"}",
       "legendFormat": "{{persistentvolume}}"
      }
     ]
    },
    {
     "title": "PV Status",
     "type": "stat",
     "description": "Status of persistent volume - Available/Bound/Failed/Pending/Released",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase)(kube_persistentvolume_status_phase{persistentvolume=~\"$volume\"})",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "PVC Info",
     "type": "stat",
     "description": "Persistent volume claim count",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_info{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", persistentvolumeclaim=~\"$volume_claim\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVC Status",
     "type": "stat",
     "description": "Status of persistent volume claim- Bound/Lost/Pending",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase) (kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", persistentvolumeclaim=~\"$volume_claim\"})",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "PVC Reference",
     "type": "stat",
     "description": "Persistent volume claim reference",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (kube_persistentvolume_claim_ref{persistentvolume=~\"$volume\"})",
       "legendFormat": "{{persistentvolume}}"
      }
     ]
    },
    {
     "title": "PVC Access Mode",
     "type": "stat",
     "description": "Type of access mode for Persistent volume claim",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_access_mode{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", persistentvolumeclaim=~\"$volume_claim\"}",
       "legendFormat": "{{persistentvolumeclaim}} {{access_mode}}"
      }
     ]
    },
    {
     "title": "PV Status",
     "type": "timeseries",
     "description": "Status of persistent volume - Available/Bound/Failed/Pending/Released",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolume_status_phase{persistentvolume=~\"$volume\"}",
       "legendFormat": "{{persistentvolume}}-{{phase}}"
      }
     ]
    },
    {
     "title": "PV Capacity Bytes",
     "type": "timeseries",
     "description": "Persistent volume capacity bytes",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_persistentvolume_capacity_bytes{persistentvolume=~\"$volume\"}",
       "legendFormat": "{{persistentvolume}}"
      }
     ]
    },
    {
     "title": "PVC Status",
     "type": "timeseries",
     "description": "Status of persistent volume claim- Bound/Lost/Pending",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", persistentvolumeclaim=~\"$volume_claim\"}",
       "legendFormat": "{{persistentvolumeclaim}}-{{phase}}"
      }
     ]
    },
    {
     "title": "PVC Request Bytes",
     "type": "timeseries",
     "description": "Persistent volume claim resource requests storage bytes",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", persistentvolumeclaim=~\"$volume_claim\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats - Pods (CAdvisor) - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Container Start Time",
     "type": "stat",
     "description": "Start time of the container since unix epoch in seconds",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Processes Running in Container",
     "type": "stat",
     "description": "Number of processes running inside the container",
     "gridPos": { "h": 4, "w": 7, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_processes{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Ulimit(soft)",
     "type": "stat",
     "description": "Soft ulimit values for the container root process. Unlimited if -1",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_ulimits_soft{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "Network Received (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of bytes received",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmitted (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of bytes transmitted",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "Network Received (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of packets received",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_receive_packets_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmitted (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of packets transmitted",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_transmit_packets_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Received - Drop (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of packets dropped while receiving",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmitted - Drop (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of packets dropped while transmitting",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Received - Errors (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of errors while receiving",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_receive_errors_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmitted - Errors (total) (rate)",
     "type": "stat",
     "description": "Cumulative count of errors while transmitting",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interface) (rate(container_network_transmit_errors_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval]))>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "CPU Usage  (rate)",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed in seconds",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Bulk IO Device Usage Bytes (rate)",
     "type": "timeseries",
     "description": "Blkio device bytes usage",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_blkio_device_usage_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}-{{operation}}"
      }
     ]
    },
    {
     "title": "FS Reads Total Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of bytes read",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "FS Reads Completed Total Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of reads completed",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "FS Writes Total Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of bytes written",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "FS Writes Completed Total Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of writes completed",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "Usage Bytes",
     "type": "timeseries",
     "description": "Current memory usage, including all memory regardless of when it was accessed",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Usage Max Bytes ",
     "type": "timeseries",
     "description": "Maximum memory usage recorded",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Working Set Bytes",
     "type": "timeseries",
     "description": "Current working set",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Cache Bytes ",
     "type": "timeseries",
     "description": "Total page cache memory",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_cache{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "RSS  Bytes (Anonymous, Swap cache) ",
     "type": "timeseries",
     "description": "Size of RSS",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Usage Hit Limits (rate)",
     "type": "timeseries",
     "description": "Number of memory usage hits limits",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_memory_failcnt{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Page Faults Total (rate)",
     "type": "timeseries",
     "description": "Cumulative count of memory page faults and page major faults",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_memory_failures_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\", scope=~\"container\"}[$__rate_interval])",
       "legendFormat": "{{container}}-{{failure_type}}"
      }
     ]
    },
    {
     "title": "OOM Events Total (rate)",
     "type": "timeseries",
     "description": "Count of out of memory events observed for the container",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_oom_events_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    { "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
    {
     "title": "Received Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of bytes received",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmitted Bytes (rate)",
     "type": "timeseries",
     "description": "Cumulative count of bytes transmitted",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Received Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of packets received",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_packets_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmitted Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of packets transmitted",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_packets_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Received - Drop Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of packets dropped while receiving",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmitted - Drop Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of packets dropped while transmitting",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Received - Errors Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of errors encountered while receiving",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_errors_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Transmitted - Errors Packets (rate)",
     "type": "timeseries",
     "description": "Cumulative count of errors encountered while transmitting",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_errors_total{namespace=~\"$namespace\", cluster_name=\"$cluster_name\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  }
 ]
}